#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Julen Pardo <julen.pardo@outlook.es>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN || -z "${TMPDIR}" ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Disable auto title for tmux
export DISABLE_AUTO_TITLE="true"

# Term
export TERM="xterm-256color"

# Pure theme
export PURE_GIT_COLOR=247
export PURE_PATH_COLOR=081

# ripgrep config file
export RIPGREP_CONFIG_PATH=~/.ripgreprc

# fzf
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND

# k
export K_CUSTOM_COLOR_DI='0;94'
export K_CUSTOM_COLOR_EX='0;91'
export K_CUSTOM_COLOR_LN='0;95'
export K_CUSTOM_OWNER_COLOR=249
export K_CUSTOM_GROUP_COLOR=249

# Beep
export BEEP=/usr/share/sounds/LinuxMint/stereo/dialog-question.wav
